const defaultPricing = { S: 1095, M: 1795, L: 2495, T: 5095 };

const colorMap = {
  '#F1ece1': { slug: 'ivory-sand', name: 'Ivory Sand' },
  '#b79a77': { slug: 'clay-dust', name: 'Clay Dust' },
  '#747f8c': { slug: 'slate-veil', name: 'Slate Veil' },
  '#e25303': { slug: 'molten-ember', name: 'Molten Ember' },
  '#4b5e42': { slug: 'mosstone', name: 'Mosstone' },
  '#c10c26': { slug: 'crimson-clay', name: 'Crimson Clay' },
  '#383f44': { slug: 'ashtone', name: 'Ashtone' },
  '#4c2b20': { slug: 'deep-terra', name: 'Deep Terra' },
  '#0d0d0d': { slug: 'obsidian-black', name: 'Obsidian Black' },
  '#a3b889': { slug: 'olive-dew', name: 'Olive Dew' },
};

const makeColors = (slug, hexes) =>
  hexes.map((hex) => ({
    name: colorMap[hex].name,
    hex,
    image: `/vasari/${slug}-${colorMap[hex].slug}.webp`,
    pricing: { ...defaultPricing },
  }));

const baseSizes = ['S', 'M', 'L', 'T'];

export const products = [
  {
    id: 'stria',
    title: 'Stria',
    description: 'A sleek, ribbed vase that celebrates symmetry and vertical elegance.',
    category: 'Vasari',
    baseImage: '/vasari/stria-ivory-sand.webp',
    colors: makeColors('stria', [
      '#b79a77',
      '#4c2b20',
      '#F1ece1',
      '#4b5e42',
      '#0d0d0d',
      '#747f8c',
    ]),
    sizes: baseSizes,
    dimension: { S: '10×5 cm', M: '15×7 cm', L: '20×9 cm', T: 'Varies' },
    weight: { S: '150g', M: '250g', L: '350g', T: 'Varies' },
    origin: 'India',
  },
  {
    id: 'verdant-spire',
    title: 'Verdant Spire',
    description: 'A tall, slender design evoking flourishing green growth.',
    category: 'Vasari',
    baseImage: '/vasari/verdant-spire-ivory-sand.webp',
    colors: makeColors('verdant-spire', [
      '#383f44',
      '#b79a77',
      '#4c2b20',
      '#F1ece1',
      '#4b5e42',
      '#747f8c',
    ]),
    sizes: baseSizes,
    dimension: { S: '10×5 cm', M: '15×7 cm', L: '20×9 cm', T: 'Varies' },
    weight: { S: '150g', M: '250g', L: '350g', T: 'Varies' },
    origin: 'India',
  },
  {
    id: 'coral-noir',
    title: 'Coral Noir',
    description: 'A matte-black vase textured like deep-sea coral.',
    category: 'Vasari',
    baseImage: '/vasari/coral-noir-ivory-sand.webp',
    colors: makeColors('coral-noir', [
      '#383f44',
      '#b79a77',
      '#4c2b20',
      '#F1ece1',
      '#e25303',
      '#4b5e42',
      '#747f8c',
    ]),
    sizes: baseSizes,
    dimension: { S: '10×5 cm', M: '15×7 cm', L: '20×9 cm', T: 'Varies' },
    weight: { S: '150g', M: '250g', L: '350g', T: 'Varies' },
    origin: 'India',
  },
  {
    id: 'hollow-bloom',
    title: 'Hollow Bloom',
    description: 'An airy silhouette with petals unfurling around a hollow center.',
    category: 'Vasari',
    baseImage: '/vasari/hollow-bloom-ivory-sand.webp',
    colors: makeColors('hollow-bloom', [
      '#383f44',
      '#b79a77',
      '#4c2b20',
      '#F1ece1',
      '#4b5e42',
      '#a3b889',
      '#747f8c',
    ]),
    sizes: baseSizes,
    dimension: { S: '10×5 cm', M: '15×7 cm', L: '20×9 cm', T: 'Varies' },
    weight: { S: '150g', M: '250g', L: '350g', T: 'Varies' },
    origin: 'India',
  },
  {
    id: 'lunar-shell',
    title: 'Lunar Shell',
    description: 'Rounded ridges reminiscent of a moonlit seashell.',
    category: 'Vasari',
    baseImage: '/vasari/lunar-shell-ivory-sand.webp',
    colors: makeColors('lunar-shell', [
      '#383f44',
      '#b79a77',
      '#4c2b20',
      '#F1ece1',
      '#4b5e42',
      '#747f8c',
    ]),
    sizes: baseSizes,
    dimension: { S: '10×5 cm', M: '15×7 cm', L: '20×9 cm', T: 'Varies' },
    weight: { S: '150g', M: '250g', L: '350g', T: 'Varies' },
    origin: 'India',
  },
  {
    id: 'obsidian-fold',
    title: 'Obsidian Fold',
    description: 'Crisp geometric folds finished in a glossy volcanic glaze.',
    category: 'Vasari',
    baseImage: '/vasari/obsidian-fold-ivory-sand.webp',
    colors: makeColors('obsidian-fold', [
      '#383f44',
      '#b79a77',
      '#4c2b20',
      '#F1ece1',
      '#4b5e42',
      '#747f8c',
    ]),
    sizes: baseSizes,
    dimension: { S: '10×5 cm', M: '15×7 cm', L: '20×9 cm', T: 'Varies' },
    weight: { S: '150g', M: '250g', L: '350g', T: 'Varies' },
    origin: 'India',
  },
  {
    id: 'sage-weave',
    title: 'Sage Weave',
    description: 'Interlaced patterns glazed in calming sage tones.',
    category: 'Vasari',
    baseImage: '/vasari/sage-weave-ivory-sand.webp',
    colors: makeColors('sage-weave', [
      '#383f44',
      '#b79a77',
      '#4c2b20',
      '#F1ece1',
      '#4b5e42',
      '#747f8c',
    ]),
    sizes: baseSizes,
    dimension: { S: '10×5 cm', M: '15×7 cm', L: '20×9 cm', T: 'Varies' },
    weight: { S: '150g', M: '250g', L: '350g', T: 'Varies' },
    origin: 'India',
  },
  {
    id: 'twist-bloom',
    title: 'Twist Bloom',
    description: 'A twisting profile that reveals organic petal layers.',
    category: 'Vasari',
    baseImage: '/vasari/twist-bloom-ivory-sand.webp',
    colors: makeColors('twist-bloom', [
      '#383f44',
      '#b79a77',
      '#4c2b20',
      '#F1ece1',
      '#4b5e42',
      '#747f8c',
    ]),
    sizes: baseSizes,
    dimension: { S: '10×5 cm', M: '15×7 cm', L: '20×9 cm', T: 'Varies' },
    weight: { S: '150g', M: '250g', L: '350g', T: 'Varies' },
    origin: 'India',
  },
  {
    id: 'amber-prism',
    title: 'Amber Prism',
    description: 'Translucent amber tones cut into a multifaceted shape.',
    category: 'Vasari',
    baseImage: '/vasari/amber-prism-ivory-sand.webp',
    colors: makeColors('amber-prism', [
      '#383f44',
      '#b79a77',
      '#4c2b20',
      '#F1ece1',
      '#4b5e42',
      '#747f8c',
    ]),
    sizes: baseSizes,
    dimension: { S: '10×5 cm', M: '15×7 cm', L: '20×9 cm', T: 'Varies' },
    weight: { S: '150g', M: '250g', L: '350g', T: 'Varies' },
    origin: 'India',
  },
];
