export const colorMap = {
  '#F1ece1': 'ivory-sand',
  '#b79a77': 'clay-dust',
  '#747f8c': 'slate-veil',
  '#e25303': 'molten-ember',
  '#4b5e42': 'mosstone',
  '#c10c26': 'crimson-clay',
  '#383f44': 'ashtone',
  '#4c2b20': 'deep-terra',
  '#0d0d0d': 'obsidian-black',
};

const colors = Object.keys(colorMap);
const makeImages = (slug) =>
  Object.fromEntries(
    colors.map((hex) => [hex, `/vasari/${slug}-${colorMap[hex]}.webp`])
  );

export const products = [
  {
    id: 'stria',
    title: 'Stria',
    description: 'A sleek, ribbed vase that celebrates symmetry and vertical elegance.',
    category: 'Vasari',
    colors,
    images: makeImages('stria'),
    basePrice: {
      small: 1095,
      medium: 1795,
      large: 2495,
      set: 5095,
    },
    dimension: 'Varies by size',
    weight: 'Approx. 300g',
    origin: 'India',
  },
  {
    id: 'verdant-spire',
    title: 'Verdant Spire',
    description: 'A tall, slender design evoking flourishing green growth.',
    category: 'Vasari',
    colors,
    images: makeImages('verdant-spire'),
    basePrice: {
      small: 1095,
      medium: 1795,
      large: 2495,
      set: 5095,
    },
    dimension: 'Varies by size',
    weight: 'Approx. 300g',
    origin: 'India',
  },
  {
    id: 'coral-noir',
    title: 'Coral Noir',
    description: 'A matte-black vase textured like deep-sea coral.',
    category: 'Vasari',
    colors,
    images: makeImages('coral-noir'),
    basePrice: {
      small: 1095,
      medium: 1795,
      large: 2495,
      set: 5095,
    },
    dimension: 'Varies by size',
    weight: 'Approx. 300g',
    origin: 'India',
  },
  {
    id: 'hollow-bloom',
    title: 'Hollow Bloom',
    description: 'An airy silhouette with petals unfurling around a hollow center.',
    category: 'Vasari',
    colors,
    images: makeImages('hollow-bloom'),
    basePrice: {
      small: 1095,
      medium: 1795,
      large: 2495,
      set: 5095,
    },
    dimension: 'Varies by size',
    weight: 'Approx. 300g',
    origin: 'India',
  },
  {
    id: 'lunar-shell',
    title: 'Lunar Shell',
    description: 'Rounded ridges reminiscent of a moonlit seashell.',
    category: 'Vasari',
    colors,
    images: makeImages('lunar-shell'),
    basePrice: {
      small: 1095,
      medium: 1795,
      large: 2495,
      set: 5095,
    },
    dimension: 'Varies by size',
    weight: 'Approx. 300g',
    origin: 'India',
  },
  {
    id: 'obsidian-fold',
    title: 'Obsidian Fold',
    description: 'Crisp geometric folds finished in a glossy volcanic glaze.',
    category: 'Vasari',
    colors,
    images: makeImages('obsidian-fold'),
    basePrice: {
      small: 1095,
      medium: 1795,
      large: 2495,
      set: 5095,
    },
    dimension: 'Varies by size',
    weight: 'Approx. 300g',
    origin: 'India',
  },
  {
    id: 'sage-weave',
    title: 'Sage Weave',
    description: 'Interlaced patterns glazed in calming sage tones.',
    category: 'Vasari',
    colors,
    images: makeImages('sage-weave'),
    basePrice: {
      small: 1095,
      medium: 1795,
      large: 2495,
      set: 5095,
    },
    dimension: 'Varies by size',
    weight: 'Approx. 300g',
    origin: 'India',
  },
  {
    id: 'twist-bloom',
    title: 'Twist Bloom',
    description: 'A twisting profile that reveals organic petal layers.',
    category: 'Vasari',
    colors,
    images: makeImages('twist-bloom'),
    basePrice: {
      small: 1095,
      medium: 1795,
      large: 2495,
      set: 5095,
    },
    dimension: 'Varies by size',
    weight: 'Approx. 300g',
    origin: 'India',
  },
  {
    id: 'amber-prism',
    title: 'Amber Prism',
    description: 'Translucent amber tones cut into a multifaceted shape.',
    category: 'Vasari',
    colors,
    images: makeImages('amber-prism'),
    basePrice: {
      small: 1095,
      medium: 1795,
      large: 2495,
      set: 5095,
    },
    dimension: 'Varies by size',
    weight: 'Approx. 300g',
    origin: 'India',
  },
];
